INSERT INTO tblStats(dtName, dtBeschreibung)
VALUES ('Max Leben' , 'Höhe des Schadens, den Sie vor dem Tod erleiden können'),
       ('Leben Regeneration','Sie regenerieren 0,0x HP pro Sekunde. Es sei denn, Sie haben Folter, wo Sie jede Sekunde 3 HP regenerieren'),
       ('Leben stehlen','Deine Angriffe haben eine x%ige Chance, dich für 1HP zu heilen'),
       ('Schaden','	Deine Angriffe verursachen x % mehr Schaden, wirken sich aber nicht auf technische Geschütztürme oder Minen aus'),
       ('Nahkampfschaden','Deine Nahkampfangriffe verursachen x zusätzlichen Schaden'),
       ('Fernschaden','Deine Fernangriffe verursachen x zusätzlichen Schaden'),
       ('Elementarschäden','Lässt dich Elementarangriffe x Schaden verursachen'),
       ('Angriffsgeschwindigkeit','Sie greifen x% schneller an. Gilt auch für Fernkampfwaffen, aber nicht für technische Türme oder Minen'),
       ('Crit Chance','Deine Waffen haben eine x erhöhte Chance, einen kritischen Treffer auszuteilen'),
       ('Ingenieurwesen','Erhöht die Kraft Ihrer Strukturen. Die anderen Werte beeinflussen keine Strukturen, aber Specials (Piercing, Hüpfen, Explosion usw.)'),
       ('Reichweite','Die maximale Reichweite deiner Waffen wird um x erhöht. Eine höhere Reichweite erhöht auch die Abklingzeit von Nahkampfwaffen. (längere Fahrstrecke)'),
       ('Rüstung','Du nimmst 4% weniger Schaden pro Rüstung (nicht linear)'),
       ('Ausweichen','Sie haben eine x%ige Chance, Angriffen auszuweichen'),
       ('Geschwindigkeit','Sie bewegen sich x% schneller'),
       ('Glück','Du hast eine x % höhere Chance, Gegenstände oder Verbrauchsmaterialien zu finden, wenn du Feinde tötest. Erhöht auch die Seltenheit der Gegenstände im Shop und Level-Upgrades'),
       ('Ernte','Du verdienst x Materialien und XP am Ende einer Welle. Erhöht um 5% jedes Mal, wenn es aktiviert wird');

INSERT INTO tblWeapon (dtName)
VALUES ('Kakteen-Club'),
       ('Hubschrauber'),
       ('Kreissäge'),
       ('Dieb Dolch'),
       ('Faust'),
       ('Flammende Schlagringe aus Messing'),
       ('Geisteraxt'),
       ('Geist Feuerstein'),
       ('Hammer'),
       ('Hand'),
       ('Beil'),
       ('Messer'),
       ('Blitz Messer'),
       ('Planke'),
       ('Plasma-Vorschlaghammer'),
       ('Power-Faust'),
       ('Fels'),
       ('Schere'),
       ('Schraubenzieher'),
       ('Speer'),
       ('Stacheliger Schild'),
       ('Stock'),
       ('Schwert'),
       ('Donnerschwert'),
       ('Fackel'),
       ('Schraubenschlüssel'),
       ('Armbrust'),
       ('Doppelläufige Schrotflinte'),
       ('Flammenwerfer'),
       ('Geisterzepter'),
       ('Laserkanone'),
       ('Medizinische Pistole'),
       ('Minigun'),
       ('Nukleare Trägerrakete'),
       ('Obliterator'),
       ('Pistole'),
       ('Kartoffelwerfer'),
       ('Raketenwerfer'),
       ('Reißwolf'),
       ('Shuriken'),
       ('Steinschleuder'),
       ('SMG'),
       ('Scharfschützengeschütz'),
       ('Taser'),
       ('Zauberstab');

INSERT INTO tblItem (dtName)
VALUES ('Säure'),
       ('Alien Baby'),
       ('Außerirdische Augen'),
       ('Alien Magie'),
       ('Außerirdische Zunge'),
       ('Alien Wurm'),
       ('Legierung'),
       ('Amboss'),
       ('Baby Elefant'),
       ('Baby Gecko'),
       ('Baby mit Bart'),
       ('Tasche'),
       ('Halstuch'),
       ('Banner'),
       ('Barrikade'),
       ('Fledermaus'),
       ('Beanie'),
       ('Bohnenlehrer'),
       ('Große Arme'),
       ('Schwarzer Gürtel'),
       ('Augenbinde'),
       ('Blutspende'),
       ('Blutegel'),
       ('Kochendes Wasser'),
       ('Buch'),
       ('Melone'),
       ('Boxhandschuh'),
       ('Gebrochener Mund'),
       ('Schmetterling'),
       ('Kuchen'),
       ('Lagerfeuer'),
       ('Kerze'),
       ('Umhang'),
       ('Chamäleon'),
       ('Holzkohle'),
       ('Krallenbaum'),
       ('Klee'),
       ('Kaffee'),
       ('Kogge'),
       ('Community-Unterstützung'),
       ('Kompass'),
       ('Coupon'),
       ('Krone'),
       ('Süßer Affe'),
       ('Cyberball'),
       ('Zyklopenwurm'),
       ('Gefährlicher Hase');
#Nicht alles

INSERT INTO tblCharacter (dtName)
VALUES ('Gut abgerundet'),
       ('Schläger'),
       ('Verrückt'),
       ('Förster'),
       ('Magier'),
       ('Stämmig'),
       ('Alt'),
       ('Glücklich'),
       ('Mutant'),
       ('Generalist'),
       ('Laut'),
       ('Multitasker'),
       ('Wildling'),
       ('Pazifist'),
       ('Gladiator'),
       ('Sparer'),
       ('Krank'),
       ('Bauer'),
       ('Geist'),
       ('Schnell'),
       ('Schnell'),
       ('Ingenieur'),
       ('Forscher'),
       ('Arzt'),
       ('Jäger'),
       ('Handwerker'),
       ('Waffenhändler'),
       ('Wimpel'),
       ('Einarmig'),
       ('Stier'),
       ('Soldat'),
       ('Masochist'),
       ('Ritter'),
       ('Dämon');

INSERT INTO tblEnemies (dtName, dtHP, dtHPProWave, dtSpeed, dtDamage, dtDamageProWave, dtMaterialDrop)
VALUES ('Baum',10,5,0,0,0,3),
       ('Baby Alien',2,2,250,1,0.6,1),
       ('Verfolger',1,1,380,1,0.6,1),
       ('Spitter',8,1,200,1,0.6,1),
       ('Ladegerät',4,2.5,400,1,0.85,1),
       ('Verfolger',10,24,150,1,1.2,3),
       ('Kraftmeier',20,11,300,2,0.85,3),
       ('Puffer',20,3,150,1,0.6,2),
       ('Fliegen',15,4,350,1,0.85,1),
       ('Beschädigter Baum',15,13,0,1,1.1,0),
       ('Heiler',10,8,400,1,0.85,2),
       ('Plünderer',50,25,350,1,0.85,8),
       ('Helm Alien',8,3,250,1,1.0,1),
       ('Flossen-Alien',12,2,400,1,1.0,1),
       ('Rogener',10,1,120,1,0.85,1),
       ('Junkie',20,5,350,1,1.0,1),
       ('Gehörnter Bruiser',30,22,300,1,1.15,3),
       ('Gehörntes Ladegerät',12,5,425,1,1.1,1),
       ('Slasher Ei',5,3,0,1,0.25,1),
       ('Haumesser',50,25,275,1,1.15,3),
       ('Tentakel',100,20,175,1,1.0,1),
       ('Nashorn',1,750,250,1,1.5,10),
       ('Metzger',1,750,200,1,1.5,10),
       ('Mönch',1,700,250,1,1.5,10),
       ('Raubtier',29900,0,300,29.5,0,0),
       ('Aufrufende',29900,0,200,29.5,0,0);

INSERT INTO tblCharacterStartWeapon (fiCharacter, fiWeapon, dtCount)
VALUES (2,5,1),
       (3,12,1),
       (4,36,1),
       (13,22,1),
       (22,26,1);